export default {
    MENTOR: 'mentor',
    URGENT: 'urgent',
    WARNING: 'warning',
    SUCCESS: 'success',
    INFO: 'Info',
    MENTOR_BADGE: 'mentorBadges',
    CONTENT: 'content',
    COMMENTS: 'comments',
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    DESCRIPTOR: "descriptor",
    MULTISELECT: 'multi-Select',
    DESKTOP: 'desktop',
    SECONDARY: 'secondary',
    MOBILE: 'mobile',
    PRIMARY: 'primary',
    CLOSE: 'close',
    SELFSEASEND: 'selfseaSend',
    LARGEINPUT: 'largeInput',
    LARGETEXTAREA: 'largeTextarea',
    LABEL: 'label',
    SWITCHBUTTON: 'switchButton',
    ENABLE: "enable"

};