default_platform(:android)

platform :android do
  before_all do
    setup_circle_ci
  end

  desc "Runs all the tests"
  lane :test do |options|
    gradle(task: "test")
  end

  desc "Submit a new staging build"
  lane :submit_build do
    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV["HOME"] + "/keystore.jks",
        "android.injected.signing.store.password" => ENV["ANDROID_KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "selfsea",
        "android.injected.signing.key.password" =>  ENV["ANDROID_KEYSTORE_PASSWORD"]
      }
    )
    upload_to_play_store(
      track: "internal",
      release_status: 'draft'
    )
  end

  desc "Generate a development build"
  lane :build_development do
    gradle(task: "bundle", build_type: "Debug")
  end

end
